### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by brightsunp** [jobbole/translation-playground#1]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：

> Python, Data science, Machine learning, Tensorflow

2. 在职/在校：

> 在职

3. 每周的空闲时间：

> 工作日 8pm~10pm；周末 almost-full-time

4. 能否科学上网：

> 是

5. 有无翻译经验（如果有，欢迎附上链接）：

> 无

6. 从何处了解到伯乐在线翻译组/为何加入：

> 经常阅读伯乐在线文章，受益匪浅/希望能回馈社区

7. 简单自我介绍：

> 程序员，机器学习爱好者

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已经发送

**Comment by hanxiaomax** [comment]
通过
