### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by kangqiwang** [jobbole/translation-playground#10]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：爬虫，机器学习，深度学习，图像处理
2. 在职/在校：在职
3. 每周的空闲时间：3个小时
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：很感兴趣，愿意为社区广大程序员做出贡献
7. 简单自我介绍：

你好我是在英国实习的硕士生，自认为英文能力还行，平时时间不是特别多。但是我愿意利用自己的空余时间为社区做出小小的微薄之力，之前只有给实验室同学做过Javafx的教程翻译，对比很多人有翻译经验，我只是一个会点技术的程序员。希望有机会能为这里做出贡献，谢谢

Kang

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
文章已经发到kq19921207@gmail.com清查收

**Comment by kangqiwang** [comment]
提醒下，翻译已经回复了，不好意思，正好项目提交，晚了点

**Comment by hanxiaomax** [comment]
抱歉，之前邮件被qq邮箱错误分类了，我刚才已经回复您了
