### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by qz267** [jobbole/translation-playground#16]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：性能测试，系统性能优化，系统性能监控，高可用性分布式系统
2. 在职/在校：在职
3. 每周的空闲时间：6hr
4. 能否科学上网：可以
5. 有无翻译经验（如果有，欢迎附上链接）：木有
6. 从何处了解到伯乐在线翻译组/为何加入：以前一直订阅伯乐在线，看过好多你们的文章
7. 简单自我介绍：本名就不说啦，国内毕业于华南理工大学计算机科学与技术学院，之后就职于微软亚洲研究院，参与Bing搜索引擎的开发与测试工作。两年后赴美，在NYU完成了CS的硕士，之后曾就职于 Ebay, Bloomberg等多家公司，目前在Shutterstock负责系统性能测试及优化

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
大佬，试译发过去了。@qz267
