### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by yiting007** [jobbole/translation-playground#17]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：软件开发
2. 在职/在校：在职
3. 每周的空闲时间：大概10小时左右吧
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：没有
6. 从何处了解到伯乐在线翻译组/为何加入：几年前就看伯乐在线，虽然是偶尔翻翻但是总能找到有趣的文章
7. 简单自我介绍：
你好，我叫Yiting，在西雅图工作，是一名软件工程师。平时会随便看看技术文章，中英文都会看。关注伯乐在线挺久了，想试试参与翻译 :)

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
hanxiaomax@qq.com 麻烦您给我的邮箱发个邮件，带上这个issue的链接，我把试译文章发您~
