### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by ABBlankSpace** [jobbole/translation-playground#19]
*标题请填写：译者申请*

1. 擅长领域：C++ 机器学习 深度学习 大数据系统
2. 在职/在校：在校
3. 每周的空闲时间：周六周日
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：木有
6. 从何处了解到伯乐在线翻译组/为何加入：之前看过博客觉得很有用
7. 简单自我介绍：我是计算机专业的硕士研究生，研究方向是情感分析，英语水平还不错，六级603分~每个季度翻译一篇这个基本要求是没问题的~

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已经发送到您的邮箱了
