### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by TwIStOy** [jobbole/translation-playground#2]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：C++、Python
2. 在职/在校：在职
3. 每周的空闲时间：工作日 11:30 pm - 2:30am，周末 1:00pm - 7:30pm
4. 能否科学上网：可以
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：读社区的文章很久了，希望为社区做些事情
7. 简单自我介绍：

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已经发送，请注意查收邮件

**Comment by hanxiaomax** [comment]
不好意思，暂未通过
