### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by xuJian2014** [jobbole/translation-playground#21]
*标题请填写：译者申请*

1. 擅长领域：Java
2. 在职/在校：在职
3. 每周的空闲时间：周一至周五：晚八点至十点，周末空闲
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：有，[Java ArrayList的不同排序方法](http://www.importnew.com/17211.html)，[StackOverflow Java API 问题 Top10](http://www.importnew.com/18881.html)
6. 从何处了解到伯乐在线翻译组/为何加入：借此平台，一起共享和学习IT知识
7. 简单自我介绍：17年硕士毕业，现从事Java领域开发工作

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
以前在伯乐翻译过的话就不用再试译了
