### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by yuanfengyun** [jobbole/translation-playground#24]
*标题请填写：译者申请*

1. 擅长领域：c++、lua、nginx、golang、redis、mongodb等服务器相关
2. 在职/在校：在职
3. 每周的空闲时间：5小时
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：github
7. 简单自我介绍：

工作7年的后端程序员，在网上也分享一些教程和开源项目。
https://github.com/yuanfengyun
https://yungege.ke.qq.com/

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
已经给您发送试译文章了
