### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by HuihuangZhang** [jobbole/translation-playground#31]
*标题请填写：译者申请*

1. 擅长领域：nodejs
2. 在职/在校：在职
3. 每周的空闲时间：周末
4. 能否科学上网：可以
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：网页看到的
7. 简单自我介绍：
新晋码农，在腾讯和头条任职过，目前在头条。主要负责nodejs后台开发。向学习更多新知识，在自己的能力范围内，也帮助别人学习更多知识。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
麻烦您给我的邮箱发个邮件，我把试译文章发给您

**Comment by HuihuangZhang** [comment]
> 麻烦您给我的邮箱发个邮件，我把试译文章发给您

不好意思，我发邮件去了hanxiaomax@qq.com这个邮箱的。
我的联系邮箱是1046604957@qq.com

**Comment by hanxiaomax** [comment]
看到了，被邮箱当垃圾邮件屏蔽了

**Comment by HuihuangZhang** [comment]
我已经把翻译后的文章回复回去了，我怕又被当成垃圾邮件，所以在这里提一下哈
