### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by wuruoyu** [jobbole/translation-playground#34]
*标题请填写：译者申请*

1. 擅长领域：强化学习 / 分布式系统
2. 在职/在校：在校
3. 每周的空闲时间：周末
4. 能否科学上网：在美国
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：github上看到
7. 简单自我介绍：是美国的一个一年级PhD。想做点公益活动充实一下自己，也希望能为计算机方面的中文资源做点贡献

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
已发送哦~
