### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by demuxin** [jobbole/translation-playground#38]
*标题请填写：译者申请*

1. 擅长领域：Python，深度学习，OpenCV，计算机视觉
2. 在职/在校：在职
3. 每周的空闲时间：晚上九点之后，周末
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：经常在伯乐在线上看技术文章，发现好多都是翻译国外的优秀文章，很佩服也很感谢自愿翻译文章的人，对于知识传播起到很大的作用，所以我也想成为其中的一员。
7. 简单自我介绍：
我于17年从山东大学毕业，自动化专业，英语六级500+，工作后通过自学成功转行做图像识别，看了很多英语文献，深知英语对这个行业的重要性，想要提升自己的英语水平，同时又能为知识的传播做出贡献，所以请求加入翻译组。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译邮件收到了吗？

**Comment by zxdefying** [comment]
> 试译邮件收到了吗？
