### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by kaluosifa** [jobbole/translation-playground#39]
*标题请填写：译者申请*

1. 擅长领域：C
2. 在职/在校：在校
3. 每周的空闲时间：周末
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：jobbole/awesome-c-cn
7. 简单自我介绍：
一个非计算机专业却对编程感兴趣的小菜鸟。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
请问试译文章您收到了吗

**Comment by kaluosifa** [comment]
还没有呢。

**Comment by kaluosifa** [comment]
还没有呢。

发送自 Windows 10 版邮件应用

发件人: Lingfeng_Ai
发送时间: 2019年4月7日 22:08
收件人: jobbole/translation-playground
抄送: kaluosifa; Author
主题: Re: [jobbole/translation-playground] 译者申请 (#39)

请问试译文章您收到了吗

**Comment by hanxiaomax** [comment]
已发送
