### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by ThreeDrop** [jobbole/translation-playground#4]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：R语言 Matlab
2. 在职/在校：在校
3. 每周的空闲时间：晚上和周末
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：暂无
6. 从何处了解到伯乐在线翻译组/为何加入：搜索爬虫文章时看到
7. 简单自我介绍：北大硕士毕业，准备赴法攻读博士学位，对数据分析很感兴趣。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
@yaoyitong 试译文章已经发送
