### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by yanxutao89** [jobbole/translation-playground#40]
*标题请填写：译者申请*

1. 擅长领域：Java Python
2. 在职/在校：在职
3. 每周的空闲时间：20
4. 能否科学上网：是
5. 有无翻译经验（如果有，欢迎附上链接）：兼职笔译近半年
6. 从何处了解到伯乐在线翻译组/为何加入：官网
7. 简单自我介绍：

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
请查收试译文章
