### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by CornPrincess** [jobbole/translation-playground#43]
*标题请填写：译者申请*

1. 擅长领域：Java Python Blockchain
2. 在职/在校：在职
3. 每周的空闲时间：周末两天
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：无，但平常经常看英文文档
6. 从何处了解到伯乐在线翻译组/为何加入：通过hanxiaomax 的github了解
7. 简单自我介绍：
我是2019年新入职的程序员，主要语言是python和java，对前端和web开发以及小程序感兴趣，正在自学前端，加入的目的是想和大家一起翻译高质量的英文技术文章，一起成长。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
麻烦您发个邮件给我我把文章发给您

**Comment by CornPrincess** [comment]
之前给您qq邮箱发送issue链接了，我邮箱是qwskyz@163.com

**Comment by CornPrincess** [comment]
试译文已发送邮箱，请查收。
