### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by siqliu** [jobbole/translation-playground#46]
*标题请填写：译者申请*

1. 擅长领域：后端开发
2. 在职/在校：在职
3. 每周的空闲时间：3-4小时
4. 能否科学上网：可以
5. 有无翻译经验（如果有，欢迎附上链接）：无
6. 从何处了解到伯乐在线翻译组/为何加入：微博关注，偶尔看一些推荐文章。
7. 简单自我介绍：目前在新加坡工作，希望通过文章翻译锻炼英语及技术类文章的写作能力。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by siqliu** [comment]
译文已回复

**Comment by hanxiaomax** [comment]
回复给您了
