### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by youngLake** [jobbole/translation-playground#48]
*标题请填写：译者申请*

1. 擅长领域：Java,Spring,高并发。
2. 在职/在校：在职。
3. 每周的空闲时间：法定节假日(偶尔下班后也有)。
4. 能否科学上网：目前不能。
5. 有无翻译经验（如果有，欢迎附上链接）：无翻译经验。
6. 从何处了解到伯乐在线翻译组/为何加入：在伯乐看技术文章时看到了下面的链接/加入的原因是业余喜爱英语，很久之前就有了想进翻译组的想法，想进一步的增长语言水平，而贵翻译组的是翻译国外优秀技术文章的，在给大家分享的同时也能增长自己的技术深度。
7. 简单自我介绍：我是一名在北京工作的Java码农，自学英语快3年了(距离5/27还差3天整3年)。工作中解决问题的时候或者学习新的知识的时候偶尔会看一些国外的(官方)网站，平时也会看外刊和英文原著。翻译水平也很低(应该是处于那种只能意会不能言传的那种状态或者只会直译)。所以想尝试一下，一来可以分享给大家，二来也是锻炼的一种方式。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
(试译：如果这看起来不太对，可以换一种不同的类型。)

这个是啥意思？

**Comment by youngLake** [comment]
@hanxiaomax 抱歉，打错了

**Comment by hanxiaomax** [comment]
文章收到了么

**Comment by youngLake** [comment]
抱歉，我的邮箱才收到GitHub发的邮件。请问文章是去哪里找？还是邮箱发送的？如果是邮箱发送的话我没有收到。请您告知一下，不胜感激！

**Comment by youngLake** [comment]
您好，我的试译昨天晚上已经发给您了。
