### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by qxdo** [jobbole/translation-playground#7]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：Java,Java Web
2. 在职/在校：目前大四在职
3. 每周的空闲时间：2-3天
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：暂无
6. 从何处了解到伯乐在线翻译组/为何加入：朋友介绍，为了拓宽一下自己的知识能力，以及提高自己的翻译能力。
7. 简单自我介绍：本人是软件工程大四的一名学生，对技术方面的东西比较感兴趣，偶然通过朋友的介绍了解到有这么一个组织，希望加入。

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译文章已经发送给您了

**Comment by hanxiaomax** [comment]
通过
