### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by 0xkookoo** [jobbole/translation-playground#8]
*标题请填写：译者申请*
*lable请选择：M-Apply*

1. 擅长领域：Java，后端开发，算法，数据结构，机器学习，数据挖掘，区块链
2. 在职/在校：在校
3. 每周的空闲时间：每周都空闲
4. 能否科学上网：能
5. 有无翻译经验（如果有，欢迎附上链接）：有，https://github.com/apachecn
6. 从何处了解到伯乐在线翻译组/为何加入：从 Github 来，贡献力量
7. 简单自我介绍：在校学生撸技术

-----------

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
试译已经发送咯
